# Generated by Django 3.0.5 on 2021-01-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webupdate',
            name='web_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website_tracking.WebSource'),
        ),
    ]
