# Generated by Django 3.0.5 on 2021-01-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_tracking', '0002_webupdate_web_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='webupdate',
            name='user_updated_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='webupdate',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(-1, 'Rejected'), (0, 'Draft'), (1, 'Pending'), (2, 'Published'), (5, 'On Hold'), (3, 'Pending Related Url'), (4, 'Incomplete Fetched'), (6, 'Source Ner')], db_index=True, default=0),
        ),
    ]
