# Generated by Django 3.0.5 on 2021-02-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penseive', '0008_auto_20201126_1513'),
        ('website_tracking', '0004_auto_20210125_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='webupdate',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='penseive.ContentType'),
        ),
    ]
