# Generated by Django 3.0.5 on 2021-03-19 13:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_tracking', '0006_webclientsource_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='websource',
            name='junk_xpaths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
    ]
