# Generated by Django 3.0.5 on 2021-05-21 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_tracking', '0007_websource_junk_xpaths'),
    ]

    operations = [
        migrations.AddField(
            model_name='websource',
            name='content_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ws_cs', to='penseive.ContentSource'),
        ),
        migrations.AddField(
            model_name='websource',
            name='published_by_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ws_pbc', to='penseive.PublishedByCompany'),
        ),
    ]
