# Generated by Django 3.0.5 on 2021-05-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_tracking', '0008_auto_20210521_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webclientsource',
            name='content_source',
        ),
        migrations.RemoveField(
            model_name='webclientsource',
            name='published_by_company',
        ),
    ]
