# Generated by Django 3.0.5 on 2021-06-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_tracking', '0009_auto_20210524_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webupdate',
            name='diff_content_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
