# Generated by Django 3.0.5 on 2022-01-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_tracking', '0010_auto_20210611_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='websource',
            name='accept_cookie_xpath',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='websource',
            name='pyppeteer_networkidle',
            field=models.IntegerField(blank=True, help_text='Used to store count for how many network calls can be ignored to assume that page has been loaded fully in pyppeteer. If negative then dontpass this param while requesting', null=True),
        ),
    ]
