# Generated by Django 3.0.5 on 2022-06-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_tracking', '0011_auto_20220114_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='websource',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='websource',
            name='screenshot_sleep_time',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
