# Generated by Django 3.0.5 on 2023-08-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_tracking', '0012_auto_20220624_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websource',
            name='accept_cookie_xpath',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
