# Generated by Django 3.0.5 on 2024-10-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_tracking', '0014_auto_20230919_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='webupdate',
            name='companies_hq_locations',
            field=models.ManyToManyField(blank=True, related_name='web_update_by_companies_hq_location', to='penseive.Location'),
        ),
        migrations.AddField(
            model_name='webupdate',
            name='source_locations',
            field=models.ManyToManyField(blank=True, related_name='web_update_by_source_location', to='penseive.Location'),
        ),
        migrations.AlterField(
            model_name='webupdate',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='web_update_by_location', to='penseive.Location'),
        )
    ]
