# Generated by Django 3.0.5 on 2025-05-19 12:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_tracking', '0015_auto_20241015_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websource',
            name='accept_cookie_xpath',
        ),
        migrations.AddField(
            model_name='websource',
            name='accept_cookie_xpaths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
