# Generated by Django 3.0.5 on 2020-12-24 12:47

import contify.website_tracking.web_snapshot.models
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiffHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_web_snapshot_id', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('old_diff_html', models.TextField(blank=True, null=True)),
                ('removed_diff_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('new_web_snapshot_id', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('new_diff_html', models.TextField(blank=True, null=True)),
                ('added_diff_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_index=True, default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Processed'), (2, 'Failed')], db_index=True, default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_source_id', models.PositiveSmallIntegerField(db_index=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_index=True, default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Processed'), (2, 'Failed')], db_index=True, default=0)),
                ('hash_html', models.TextField(db_index=True, help_text='hash of the raw_html and used for uniqueness', unique=True)),
                ('raw_html', models.TextField(help_text='The web content of the URL')),
                ('raw_snapshot', models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='webtestmedia.contify.com', custom_domain='webtestmedia.contify.com', headers={'Cache-Control': 'no-transform,public,max-age=2592000,s-maxage=2592000'}, secure_urls=False), upload_to=contify.website_tracking.web_snapshot.models.WebSnapshot.image_upload_path)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiffContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_diff_html', models.TextField(blank=True, help_text='Left diff Image is generated by this', null=True)),
                ('old_diff_image', models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='webtestmedia.contify.com', custom_domain='webtestmedia.contify.com', headers={'Cache-Control': 'no-transform,public,max-age=2592000,s-maxage=2592000'}, secure_urls=False), upload_to=contify.website_tracking.web_snapshot.models.DiffContent.old_image_upload_path)),
                ('new_diff_html', models.TextField(help_text='Right diff image is generated from this')),
                ('new_diff_image', models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='webtestmedia.contify.com', custom_domain='webtestmedia.contify.com', headers={'Cache-Control': 'no-transform,public,max-age=2592000,s-maxage=2592000'}, secure_urls=False), upload_to=contify.website_tracking.web_snapshot.models.DiffContent.new_image_upload_path)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], db_index=True, default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Reject'), (2, 'Published')], db_index=True, default=0)),
                ('added_diff_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('removed_diff_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('new_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wt_right_snapshot_set', to='web_snapshot.WebSnapshot')),
                ('old_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wt_left_snapshot_set', to='web_snapshot.WebSnapshot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='diffcontent',
            constraint=models.UniqueConstraint(condition=models.Q(old_snapshot__isnull=True), fields=('old_snapshot',), name='web_snapshot_diffcontent_unique_null_old_snapshot'),
        ),
    ]
