# Generated by Django 3.0.5 on 2021-06-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_snapshot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffcontent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Reject')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='diffhtml',
            name='new_web_snapshot_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='diffhtml',
            name='old_web_snapshot_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
