# Generated by Django 3.0.5 on 2022-10-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_snapshot', '0002_auto_20210611_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffcontent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Reject'), (2, 'Published')], db_index=True, default=0),
        ),
    ]
