# Generated by Django 3.0.5 on 2023-10-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_snapshot', '0003_auto_20221021_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffhtml',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Processed'), (2, 'Failed'), (3, 'Older')], db_index=True, default=0),
        ),
    ]
